export enum IconNames {
  AcademicCap = 'academic-cap',
  Adjustments = 'Adjustments',
  Annotation = 'Annotation',
  Archive = 'Archive',
  ArrowCircleDown = 'arrow-circle-down',
  ArrowCircleLeft = 'arrow-circle-left',
  ArrowCircleRight = 'arrow-circle-right',
  arrowCircleUp = 'arrow-circle-up',
  ArrowDown = 'arrow-down',
  ArrowLeft = 'arrow-left',
  CheckCircle = 'check-circle',
  Check = 'Check',
  ExclamationCircle = 'exclamation-circle',
  EyeOff = 'eye-off',
  Eye = 'Eye',
  Login = 'Login',
  Plus = 'Plus',
  Search = 'Search',
  ShieldExclamation = 'shield-exclamation',
  XCircle = 'x-circle',
  X = 'X',
}
