export enum IconNames {
  AcademicCap = 'academic-cap',
  Adjustments = 'adjustments',
  Annotation = 'annotation',
  Archive = 'archive',
  ArrowCircleDown = 'arrow-circle-down',
  ArrowCircleLeft = 'arrow-circle-left',
  ArrowCircleRight = 'arrow-circle-right',
  arrowCircleUp = 'arrow-circle-up',
  ArrowDown = 'arrow-down',
  ArrowLeft = 'arrow-left',
  CheckCircle = 'check-circle',
  Check = 'check',
  ExclamationCircle = 'exclamation-circle',
  EyeOff = 'eye-off',
  Eye = 'eye',
  Login = 'login',
  Plus = 'plus',
  Search = 'search',
  ShieldExclamation = 'shield-exclamation',
  XCircle = 'x-circle',
  X = 'x',
}
